#!/bin/sh

#
# Copyright 2015 the original author or authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
##############################################################################

# Attempt to set APP_HOME

# Resolve links: $0 may be a link
app_path=$0

# Need this for daisy-chained symlinks.
while
    APP_HOME=${app_path%"${app_path##*/}"}  # leaves a trailing /; empty if no leading path
    [ -h "$app_path" ]
do
    ls=$(ls -ld "$app_path")
    link=${ls#*' -> '}
    case $link in             #(
      /*)   app_path=$link ;; #(
      *)    app_path=$APP_HOME$link ;;
    esac
done

# This is normally unused
# shellcheck disable=SC2034
APP_BASE_NAME=${0##*/}
# Discard trailing slash
APP_HOME=${APP_HOME%/}

# Add default JVM options here. You can also use JAVA_OPTS and GRADLE_OPTS to pass JVM options to this script.
DEFAULT_JVM_OPTS='"-Xmx64m" "-Xms64m"'

# Use the maximum available, or set MAX_FD != -1 to use that value.
MAX_FD="maximum"

warn () {
    echo "$*"
} >&2

die () {
    echo
    echo "$*"
    echo
    exit 1
} >&2

# OS specific support (must be 'true' or 'false').
cygwin=false
msys=false
darwin=false
nonstop=false
case "$(uname)" in                #(
  CYGWIN* )   cygwin=true  ;; #(
  Darwin* )   darwin=true  ;; #(
  MSYS* | MINGW* ) msys=true ;; #(
  NONSTOP* )  nonstop=true ;;
esac

CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar


# Determine the Java command to use to start the JVM.
if [ -n "$JAVA_HOME" ] ; then
    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
        # IBM's JDK on AIX uses strange locations for the executables
        JAVACMD="$JAVA_HOME/jre/sh/java"
    else
        JAVACMD="$JAVA_HOME/bin/java"
    fi
    if [ ! -x "$JAVACMD" ] ; then
        die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
else
    JAVACMD="java"
    which java >/dev/null 2>&1 || die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
fi

# Increase the maximum file descriptors if we can.
if ! "$cygwin" && ! "$darwin" && ! "$nonstop" ; then
    case $MAX_FD in #(
      max*)
        # In POSIX sh, ulimit -H is undefined. That's why the result is checked.
        MAX_FD=$(ulimit -H -n) ||
            warn "Could not query maximum file descriptor limit"
    esac
    case $MAX_FD in       #(
      '' | soft) :;;    #(
      *)
        ulimit -n "$MAX_FD" ||
            warn "Could not set maximum file descriptor limit to $MAX_FD"
    esac
fi

# Collect all arguments for the java command, stacking in reverse order:
#   * args
#   * "default" jvm args
#   * (if needed) main class name
#   * (if needed) classpath
#   * (if needed) -jar wrapper jar
#   * (if needed) -classpath classpath
#   * (if needed) -D... system properties
#   * (if needed) -X... jvm options
#   * (if needed) -Dfile.encoding=UTF-8
#   * (if needed) -Dorg.gradle.appname=$APP_BASE_NAME
#   * (if needed) -Dorg.gradle.daemon=false
#   * (if needed) -Dorg.gradle.jvmargs=-Xmx64m -Xms64m
#   * (if needed) -Dorg.gradle.logging.level=info
#   * (if needed) -Dorg.gradle.project.dir=$APP_HOME
#   * (if needed) -Dorg.gradle.user.home=$GRADLE_USER_HOME
#   * (if needed) -Dorg.gradle.wrapper.properties.file=$APP_HOME/gradle/wrapper/gradle-wrapper.properties
#   * (if needed) -Dorg.gradle.wrapper.jar=$APP_HOME/gradle/wrapper/gradle-wrapper.jar
#   * (if needed) -Dorg.gradle.wrapper.url=https\://services.gradle.org/distributions/gradle-8.2-bin.zip
#   * (if needed) -Dorg.gradle.wrapper.version=8.2
#   * (if needed) -Dorg.gradle.wrapper.checksum=...
#   * (if needed) -Dorg.gradle.wrapper.checksums=...
#   * (if needed) -Dorg.gradle.wrapper.checksums.algorithms=...
#   * (if needed) -Dorg.gradle.wrapper.checksums.algorithms.sha256=...
#   * (if needed) -Dorg.gradle.wrapper.checksums.algorithms.sha512=...
#   * (if needed) -Dorg.gradle.wrapper.checksums.algorithms.md5=...
#   * (if needed) -Dorg.gradle.wrapper.checksums.algorithms.sha1=...
#   * (if needed) -Dorg.gradle.wrapper.checksums.algorithms.sha224=...
#   * (if needed) -Dorg.gradle.wrapper.checksums.algorithms.sha384=...
#   * (if needed) -Dorg.gradle.wrapper.checksums.algorithms.sha512=...
#   * (if needed) -Dorg.gradle.wrapper.checksums.algorithms.sha3-224=...
#   * (if needed) -Dorg.gradle.wrapper.checksums.algorithms.sha3-256=...
#   * (if needed) -Dorg.gradle.wrapper.checksums.algorithms.sha3-384=...
#   * (if needed) -Dorg.gradle.wrapper.checksums.algorithms.sha3-512=...
#   * (if needed) -Dorg.gradle.wrapper.checksums.algorithms.blake2b-160=...
#   * (if needed) -Dorg.gradle.wrapper.checksums.algorithms.blake2b-256=...
#   * (if needed) -Dorg.gradle.wrapper.checksums.algorithms.blake2b-384=...
#   * (if needed) -Dorg.gradle.wrapper.checksums.algorithms.blake2b-512=...
#   * (if needed) -Dorg.gradle.wrapper.checksums.algorithms.blake2s-128=...
#   * (if needed) -Dorg.gradle.wrapper.checksums.algorithms.blake2s-160=...
#   * (if needed) -Dorg.gradle.wrapper.checksums.algorithms.blake2s-224=...
#   * (if needed) -Dorg.gradle.wrapper.checksums.algorithms.blake2s-256=...
#   * (if needed) -Dorg.gradle.wrapper.checksums.algorithms.ripemd160=...
#   * (if needed) -Dorg.gradle.wrapper.checksums.algorithms.whirlpool=...
#   * (if needed) -Dorg.gradle.wrapper.checksums.algorithms.tiger=...
#   * (if needed) -Dorg.gradle.wrapper.checksums.algorithms.sha3-224=...
#   * (if needed) -Dorg.gradle.wrapper.checksums.algorithms.sha3-256=...
#   * (if needed) -Dorg.gradle.wrapper.checksums.algorithms.sha3-384=...
#   * (if needed) -Dorg.gradle.wrapper.checksums.algorithms.sha3-512=...
#   * (if needed) -Dorg.gradle.wrapper.checksums.algorithms.blake2b-160=...
#   * (if needed) -Dorg.gradle.wrapper.checksums.algorithms.blake2b-256=...
#   * (if needed) -Dorg.gradle.wrapper.checksums.algorithms.blake2b-384=...
#   * (if needed) -Dorg.gradle.wrapper.checksums.algorithms.blake2b-512=...
#   * (if needed) -Dorg.gradle.wrapper.checksums.algorithms.blake2s-128=...
#   * (if needed) -Dorg.gradle.wrapper.checksums.algorithms.blake2s-160=...
#   * (if needed) -Dorg.gradle.wrapper.checksums.algorithms.blake2s-224=...
#   * (if needed) -Dorg.gradle.wrapper.checksums.algorithms.blake2s-256=...
#   * (if needed) -Dorg.gradle.wrapper.checksums.algorithms.ripemd160=...
#   * (if needed) -Dorg.gradle.wrapper.checksums.algorithms.whirlpool=...
#   * (if needed) -Dorg.gradle.wrapper.checksums.algorithms.tiger=...
#   * (if needed) -Dorg.gradle.wrapper.checksums.algorithms.sha3-224=...
#   * (if needed) -Dorg.gradle.wrapper.checksums.algorithms.sha3-256=...
#   * (if needed) -Dorg.gradle.wrapper.checksums.algorithms.sha3-384=...
#   * (if needed) -Dorg.gradle.wrapper.checksums.algorithms.sha3-512=...
#   * (if needed) -Dorg.gradle.wrapper.checksums.algorithms.blake2b-160=...
#   * (if needed) -Dorg.gradle.wrapper.checksums.algorithms.blake2b-256=...
#   * (if needed) -Dorg.gradle.wrapper.checksums.algorithms.blake2b-384=...
#   * (if needed) -Dorg.gradle.wrapper.checksums.algorithms.blake2b-512=...
#   * (if needed) -Dorg.gradle.wrapper.checksums.algorithms.blake2s-128=...
#   * (if needed) -Dorg.gradle.wrapper.checksums.algorithms.blake2s-160=...
#   * (if needed) -Dorg.gradle.wrapper.checksums.algorithms.blake2s-224=...
#   * (if needed) -Dorg.gradle.wrapper.checksums.algorithms.blake2s-256=...
#   * (if needed) -Dorg.gradle.wrapper.checksums.algorithms.ripemd160=...
#   * (if needed) -Dorg.gradle.wrapper.checksums.algorithms.whirlpool=...
#   * (if needed) -Dorg.gradle.wrapper.checksums.algorithms.tiger=...
exec "$JAVACMD" $DEFAULT_JVM_OPTS -classpath "$CLASSPATH" org.gradle.wrapper.GradleWrapperMain "$@"
